//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KISIBILGILERI
    {
        public int ID { get; set; }
        public string ADSOYAD { get; set; }
        public string CINSIYET { get; set; }
        public Nullable<int> YAS { get; set; }
        public Nullable<decimal> KILO { get; set; }
        public string KANGRUBU { get; set; }
        public string ILAC { get; set; }
        public string DIGERILAC { get; set; }
        public string ALERJILERI { get; set; }
        public string YANETKI { get; set; }
        public Nullable<decimal> BOY { get; set; }
        public string KITLEINDEKSI { get; set; }
    }
}
